[package]
name = "correcteur"
version = "0.1.0"
edition = "2021"
authors = ["Chaddaï Fouché <chaddai.fouche@gmail.com>"]

[dependencies]
encoding_rs = "0.8.35"
encoding_rs_io = "0.1.7"
regex = "1.11.1"
ndarray = "0.16.1"